### ISSUE TITLE
Revoking certificates problem

### ISSUE THREAD

**Issue by YannickHermans** [yourivw/LEClient#25]
Hiya,

First of all thanks for the easy to use project, much appreciated!

After registering a certificate, i tried to revoke it using the revokeCertificate method of the LEOrder class.
This resulted in an error:
"JWK embedded in revocation request must be the same public key as the cert to be revoked"

After googling for a bit i bumped into [https://community.letsencrypt.org/t/revocation-behaviour/53223
](url)
Using this logic i changed the revokeCertificate method in the LEOrder class:
`$sign = $this->connector->signRequestJWK(array('certificate' => $certificate, 'reason' => $reason), $this->connector->revokeCert);`
to
`$sign = $this->connector->signRequestJWK(array('certificate' => $certificate, 'reason' => $reason), $this->connector->revokeCert, $this->certificateKeys['private_key']);`

Inside the signRequestJWK method in the LEConnector class you default the private key to the account private key and this way you use the domain private key, which seems to do the trick.

**Comment by yourivw** [comment]
Fixed in [release 1.1.1](https://github.com/yourivw/LEClient/releases/tag/1.1.1) and the master branch.
Thanks for the proposed solution, this fixed it instantly. It's weird, because I can remember I initially created it this way, but that didn't work. Perhaps this has changed, but I couldn't find it anywere.
